### ISSUE TITLE
Adding box parsers.

### ISSUE THREAD

**Issue by NatalyMagluy** [madebyhiro/codem-isoboxer#10]
Please, provide API to add parsers for prod version of library. 
I would like to use your library with custom uuid box parser. But I do not want to use dev version and have library's code in my project.

Something like this:
``ISOBoxer.addParser('uuid', parserFunc)``

**Comment by tieleman** [comment]
Hi Nataly,

If you want to add custom parsers without changing the code, you can add them after you load the library (and before you load the ISOBMFF file) by doing something like:

`ISOBox.prototype._boxParsers['uuid'] = parserFunc`

That way your custom parser should get called whenever a `uuid` box shows up. I haven't tested it, but I don't see why that wouldn't work. You can look at any of the other parsers to see what functions are available to read the data.

**Comment by NatalyMagluy** [comment]
I'm using ES6 modules:
`import ISOBoxer from 'codem-isoboxer'`
In this case ISOBoxer has only exported parseBuffer and Utils.

**Comment by tieleman** [comment]
Merged and released as 0.2.6. Thanks!
