### ISSUE TITLE
Unsupported Uint8Array.from method on IE

### ISSUE THREAD

**Issue by bbcrddave** [madebyhiro/codem-isoboxer#27]
ISOBox.prototype._writeData requires a method which is not available in IE.

See https://github.com/Dash-Industry-Forum/dash.js/issues/1909

**Comment by qchroman** [comment]
Awesome, thank you!

**Comment by tieleman** [comment]
Thanks for the heads up. @qchroman, you said you have a quick fix ready. Do you have a pull request (or gist) for me with a polyfill for `Uint8Array.from`?

**Comment by bbert** [comment]
I have corrected in PR #28

**Comment by qchroman** [comment]
Thank you all!

**Comment by tieleman** [comment]
Just released v0.3.3. This includes the PR. Thanks!
