### ISSUE TITLE
Invalid `--no-write` option.

### ISSUE THREAD

**Issue by ksjun** [madebyhiro/codem-isoboxer#29]
`Gruntfile.js` has `--no-write` option to discard writing functions.

As `--no-write` is Grunt's own option,  please rename `write` option to other.

And it seems that `// @ifdef WRITE` block doesn't discard even `WRITE` is `false` value. Grunt process requires `undefined` value.

**Comment by bbert** [comment]
Yes you are right.
See PR #30, I have changed `--no-write` by `--no-writing` and corrected the preprocess instructions in the source files (` // @if WRITE`).
By the way, @tieleman, maybe we should provide both build versions in dist folder, one with and one w/o writing functionality.
For example:

` dist/iso_boxer(.min).js` : all options
`dist/iso_boxer_parse(.min).js` : only parsing functionality

**Comment by tieleman** [comment]
Thanks for the PR. I'm open to generating the parse-only version by default as well, as long as it keeps working/playing well with the `--boxes` option.

**Comment by bbert** [comment]
IMO the default version should contain all the stuff.
Then you could provide some other build versions like parse-only version.

Full version or parse-only building still works with `--boxes` option.

**Comment by tieleman** [comment]
I've merged the PR and opened a separate issue for the parse-only versions. Will take a look after my holidays.
