### ISSUE TITLE
Demux MP4

### ISSUE THREAD

**Issue by sassyn** [madebyhiro/codem-isoboxer#7]
Hi,

I'm looking for a way to get the raw data from a mp4 container, so I could extract the h264 video data and the AAC audio data.

The mp4 if a ISO Media, MP4 Base Media v1 with the following Metadata

ffprobe videofull.mp4 
> 
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2avc1iso6mp41
>     title           : bg2bj01low
>     encoder         : Lavf57.25.100
>     Duration: 00:00:09.17, start: 0.000000, bitrate: 1062 kb/s
>     Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 937 kb/s, 29.85 fps, 30 tbr, 15360 tbn, 60 tbc (default)
>     Metadata:
>       handler_name    : VideoHandler
>     Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
>     Metadata:
>       handler_name    : SoundHandler

I can extract the raw data using FFMPEG like this:

For Video
`fmpeg  -y -i videofull.mp4  -profile:v baseline -level 3.0 -vcodec libx264  -preset fast -b:v 500k -maxrate 500k -bufsize 1000k -r 25 -qmin 2 -qmax 22 -f h264 - > video.h264`

> file video.h264
> video.h264:JVT NAL sequence, H.264 video, baseline @ L 30
> 

For Audio
`ffmpeg  -y -i videofull.mp4   -vn -c:a libfdk_aac -b:a 128k -flags low_delay -f adts -strict -2 -> audio.aac`

> file audio.aac
> audio.aac: MPEG ADTS, AAC, v4 LC, 44.1 kHz, stereo

I want to do the same using mp4box.js without the use of ffmpeg

Is this can be done?
If so, maybe a quick example?

Thank You!

**Comment by tieleman** [comment]
Hi, you mention mp4box.js. That is an entirely different project from this, are you using codem-isoboxer or mp4box.js?

**Comment by cconcolato** [comment]
The same issue was filed on mp4box.js https://github.com/gpac/mp4box.js/issues/90. I think you can close this one.
